version: '2'

services:
  app:
    container_name: app
    restart: always
    build: ./app
    ports:
      - "8000:8000"
    volumes:
     - /home/project/app/static
    command: gunicorn -w 4 -b :8000 app:app

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
     - /www/static
    volumes_from:
     - app
